language: elixir
matrix:
  include:
    - otp_release: 18.3
      elixir: 1.3.2
    - otp_release: 19.0
      elixir: 1.3.2
addons:
  postgresql: "9.4"
services:
  - redis-server
  - postgresql
sudo: false
before_script:
  - mix ecto.create
  - mix ecto.migrate
script:
  - mix test
